Added notes to issues
MissingReferenceException: The object of type 'Transform' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.Transform.get_position () (at <e30a7bb6b3aa4f58a43c3f71ed31005c>:0)
NPCEntityDetector.IsInFOVAndInRange (UnityEngine.Transform target) (at Assets/Scripts/Entity Detection/NPCEntityDetector.cs:92)